import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  overviewSidebar: [{type: 'autogenerated', dirName: 'overview'}],

  tutorialSidebar: [
    'tutorial/index',
    {
      type: 'category',
      label: 'Client SDKs',
      link: {
        type: 'doc',
        id: 'tutorial/client-sdks/index',
      },
      items: [
        {
          type: 'category',
          label: 'TypeScript',
          link: {
            type: 'doc',
            id: 'tutorial/client-sdks/typescript/index',
          },
          items: [
            'tutorial/client-sdks/typescript/quickstart',
            'tutorial/client-sdks/typescript/queries',
            'tutorial/client-sdks/typescript/transactions',
            'tutorial/client-sdks/typescript/accounts',
            'tutorial/client-sdks/typescript/signers',
          ],
        },
        {
          type: 'category',
          label: 'JavaScript',
          link: {
            type: 'doc',
            id: 'tutorial/client-sdks/javascript/index',
          },
          items: [],
        },
      ],
    },
    {
      type: 'category',
      label: 'Convex Coins',
      items: [
        'tutorial/coins/index',
      ],
    },
    {
      type: 'category',
      label: 'Convex Lisp',
      items: [
        'tutorial/convex-lisp/index',
        'tutorial/convex-lisp/lisp-cvm',
        'tutorial/convex-lisp/lisp-guide',
        'tutorial/convex-lisp/lisp-guide-advanced',
      ],
    },
    {
      type: 'category',
      label: 'Actor Development',
      items: [
        'tutorial/actors/index',
        'tutorial/actors/concepts',
        'tutorial/actors/deployment',
        'tutorial/actors/evolution',
        'tutorial/actors/best-practices',
      ],
    },
    {
      type: 'category',
      label: 'Recipes',
      items: [
        'tutorial/recipes/index',
        'tutorial/recipes/create-account/index',
        'tutorial/recipes/managing-coins/index',
        'tutorial/recipes/coin-distributor/index',
        'tutorial/recipes/account-control/index',
      ],
    },
    'tutorial/glossary',
  ],

  productsSidebar: [{type: 'autogenerated', dirName: 'products'}],

  cadsSidebar: [{type: 'autogenerated', dirName: 'cad'}], 


  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
