convex:
  label: Convex
  permalink: /facebook
  description: Convex Foundation

welcome:
  label: Welcome
  permalink: /hello
  description: Hello tag description

community:
  label: Community
  permalink: /community
  description: Convex Developer Community

reader:
  label: Reader
  permalink: /reader
  description: Convex Reader

lisp:
  label: Lisp
  permalink: /lisp
  description: Convex Reader

cad3:
  label: CAD3
  permalink: /cad3
  description: CAD3 encoding and data formats

lattice:
  label: Lattice
  permalink: /lattice
  description: Lattice Technology

ai:
  label: AI
  permalink: /ai
  description: Artificial intelligence integrations and insights

mcp:
  label: MCP
  permalink: /mcp
  description: Model Context Protocol use cases and tools

"digital-assets":
  label: Digital Assets
  permalink: /digital-assets
  description: Tokenized assets and on-chain economy topics

automation:
  label: Automation
  permalink: /automation
  description: Automated workflows powered by Convex