convex:
  label: Convex
  permalink: /convex
  description: Convex Foundation

welcome:
  label: Welcome
  permalink: /hello
  description: Hello tag description

community:
  label: Community
  permalink: /community
  description: Convex Developer Community

reader:
  label: Reader
  permalink: /reader
  description: Convex Reader

lisp:
  label: Lisp
  permalink: /lisp
  description: Convex Reader

cad3:
  label: CAD3
  permalink: /cad3
  description: CAD3 encoding and data formats

lattice:
  label: Lattice
  permalink: /lattice
  description: Lattice Technology

ai:
  label: AI
  permalink: /ai
  description: Artificial intelligence integrations and insights

mcp:
  label: MCP
  permalink: /mcp
  description: Model Context Protocol use cases and tools

"digital-assets":
  label: Digital Assets
  permalink: /digital-assets
  description: Tokenized assets and on-chain economy topics

automation:
  label: Automation
  permalink: /automation
  description: Automated workflows powered by Convex

tokenomics:
  label: Tokenomics
  permalink: /tokenomics
  description: Token distribution, economics, and release mechanisms

cvm:
  label: CVM
  permalink: /cvm
  description: Convex Virtual Machine topics and technical details

agents:
  label: Agents
  permalink: /agents
  description: Autonomous agents and AI-driven economic actors

realtime:
  label: Real-time
  permalink: /realtime
  description: Real-time transactions and instant updates

defi:
  label: DeFi
  permalink: /defi
  description: Decentralised finance applications and protocols

web3:
  label: Web3
  permalink: /web3
  description: Web3 ecosystem and decentralised peer-to-peer applications

sql:
  label: SQL
  permalink: /sql
  description: SQL database capabilities on Convex lattice

postgresql:
  label: PostgreSQL
  permalink: /postgresql
  description: PostgreSQL compatibility and wire protocol

networking:
  label: Networking
  permalink: /networking
  description: Network protocols and connectivity

typescript:
  label: TypeScript
  permalink: /typescript
  description: TypeScript client libraries and tools

javascript:
  label: JavaScript
  permalink: /javascript
  description: JavaScript client libraries and tools

sdk:
  label: SDK
  permalink: /sdk
  description: Software development kits for Convex

developer-tools:
  label: Developer Tools
  permalink: /developer-tools
  description: Tools and libraries for Convex developers

python:
  label: Python
  permalink: /python
  description: Python client libraries and tools

documentation:
  label: Documentation
  permalink: /documentation
  description: Documentation updates and guides

java:
  label: Java
  permalink: /java
  description: Java client libraries and tools

backpressure:
  label: Backpressure
  permalink: /backpressure
  description: Flow control and backpressure patterns

netty:
  label: Netty
  permalink: /netty
  description: Netty networking framework
